image: ubuntu:16.04

stages:
  - build
  - smoke_test
  - test
  - deploy

linux-build:
  script:
    - ./configure.sh --auto
    - cd build
    - make -j4
    - make install
    - cd ..
    - mkdir -p linux/usr/
    - cp -r /usr/local/ linux/usr/
  artifacts:
    expire_in: 1 day
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
      - linux/
  stage: build
  image: butitsnotme/build-env:latest
  tags:
    - docker

linux-smoke_test:
  script:
    - cp -r linux/usr/local /usr/
    - cd /usr/local/bin/
    - ./bg --help --version
  stage: smoke_test
  tags:
    - docker
  dependencies:
    - linux-build

linux-unit_tests:
  script:
    - cp -r linux/usr/local /usr/
    - cd /usr/local/bin/
    - ./unit_tests -s
  tags:
    - docker
  dependencies:
    - linux-build

deploy_stage:
  script:
    - /bin/true
  stage: deploy
  environment: pre-release
  artifacts:
    paths:
      - linux/
  only:
    - release-*
  tags:
    - docker
  dependencies:
    - linux-build

deploy_prod:
  script:
    - /bin/true
  stage: deploy
  environment: release
  artifacts:
    paths:
      - linux/
  only:
    - releases
  tags:
    - docker
  dependencies:
    - linux-build

